### ISSUE TITLE
Improve marshalling efficiency

### ISSUE THREAD

**Issue by nemothenoone** [NilFoundation/vote-saver-protocol#6]
For the sake of making init_voting_seesion function parameters fit, it is required to refactor marshalling format: 

https://github.com/NilFoundation/crypto3-blueprint/blob/fc053b0a5f35c6878257caaa29495e375ba1675e/include/nil/crypto3/zk/components/voting/encrypted_input_voting.hpp#L48-L60

https://github.com/NilFoundation/vote-saver-protocol/blob/master/bin/cli/src/main.cpp#L267
https://github.com/NilFoundation/vote-saver-protocol/blob/master/bin/cli/src/main.cpp#L281

**Comment by NoamDev** [comment]
You can assign this to me

**Comment by nemothenoone** [comment]
Solved by #11
